"""added relationships

Revision ID: 8dd1d819cd2b
Revises: 3f097c2f7b4d
Create Date: 2025-06-20 13:53:47.563482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd1d819cd2b'
down_revision = '3f097c2f7b4d'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("restaurant_pizzas", schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pizza_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'restaurants', ['restaurant_id'], ['id'])
        batch_op.create_foreign_key(None, 'pizzas', ['pizza_id'], ['id'])



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_restaurant_pizzas_pizza_id_pizzas'), 'restaurant_pizzas', type_='foreignkey')
    op.drop_constraint(op.f('fk_restaurant_pizzas_restaurant_id_restaurants'), 'restaurant_pizzas', type_='foreignkey')
    op.drop_column('restaurant_pizzas', 'pizza_id')
    op.drop_column('restaurant_pizzas', 'restaurant_id')
    # ### end Alembic commands ###
